development:
  adapter: postgresql
  database: miletracker_development
  username: miletracker
  password: a
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: miletracker_test
  username: miletracker
  password: a
  host: localhost
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: miletracker_test
  username: miletracker
  hot: localhost
  password: <%= ENV['APP_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000
