development:
  adapter: postgresql
  database: miletracker_development
  username: miletracker
  password: a
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: miletracker_test
  username: miletracker
  password: a
  host: localhost
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
