development:
  adapter: postgresql
  database: miletracker_development
  username: miletracker
  password: <%= ENV['DEV_TEST_DB_PASSWORD'] %>
  host: localhost
  pool: 25
  timeout: 5000

test:
  adapter: postgresql
  database: miletracker_test
  username: miletracker
  password: <%= ENV['DEV_TEST_DB_PASSWORD'] %>
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= ENV['APP_DB_NAME'] %>
  username: <%= ENV['APP_DB_USER'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  password: <%= ENV['APP_DB_PASSWORD'] %>
  pool: <%= ENV['APP_DB_POOL'] %>
  timeout: <%= ENV['APP_DB_TIMEOUT'] %>
